+++
# Display name
name = "Adeline Poulain"

# Username (this should match the folder name)
authors = ["adeline-poulain"]

# Lab position or title
role = "Postdoctoral Fellow"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Postdoctoral Fellows"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = ""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "PhD in Microbiology and Immunology"
  institution = "Université de Montréal and National Research Council Canada (Montreal, Canada)"
  year = 2018

[[education.courses]]
  course = "MSc in Biotechnology R&D"
  institution = "Université Pierre et Marie Curie (Paris, France)"
  year = 2012

# Social/Academic Networking
# none
+++

*** Project
Development of an efficient and flexible stable pool platform using insect cell
culture and plasmid transfection to produce high yields of VLPs as influenza
vaccines.

*** Skills
- Development and characterization of a stable CHO cell pool platform for rapid
  production of recombinant protein.
- Optimization of plasmid expression vectors for the production of monoclonal
  antibodies in CHO cells.
- RhoA protein function in type 2 diabetes.

*** Work experience
- 2012: Internship at Cellectis (Paris, France)
- 2011: 6-month internship at Biotech Research and Innovation Center (Copenhagen, Denmark)
