+++
# Display name
name = "Laura Cervera Gracia"

# Username (this should match the folder name)
authors = ["09-laura-cervera-gracia"]

# Lab position or title
role = "Postdoctoral Fellow (2015-2017)"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Alumni"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = """Production of Influenza VLPs using Baculovirus-Sf9 cells expression
system."""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "PhD in Biotechnology"
  institution = "Universitat Autònoma de Barcelona"

[[education.courses]]
  course = "M.Sc in Biotechnology"
  institution = "Universitat Autònoma de Barcelona"

[[education.courses]]
  course = "Chemical Engineering"
  institution = "Universitat Autònoma de Barcelona"

# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "https://ca.linkedin.com/in/laura-cervera-gracia-b0327486"

[[social]]
  icon = "researchgate"
  icon_pack = "fab"
  link = "https://www.researchgate.net/profile/Laura_Cervera2"
+++

*** Work experience
- PhD with the title: Strategies to improve the production of HIV-1 VLPs by
  transient transfection of suspension mammalian cells.
- Optimization using design of experiments.
- Mammalian and insect cell culture.
- Transient transfection.
- Recombinant protein production using Baculovirus-Insect cells expression system.
- Bioreactor operation.
- Confocal microscopy.
