+++
# Display name
name = "Michelle Yen Tran"

# Username (this should match the folder name)
authors = ["michelle-yen-tran"]

# Lab position or title
role = "PhD Candidate"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["PhD Candidates"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = """Process Intensification and Functionality Assessment of Lentiviral
Vectors."""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education 
[[education.courses]]
  course = "BSc in Bioengineering"
  institution = "University of California, Berkeley (USA)"
  year = "2008-2012"

[[education.courses]]
  course = "Master's student, fast-tracked into the PhD Program (Oct 2018)"
  year = "2017-"
  institution = "McGill University (Montreal, Canada)"
  
# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "https://www.linkedin.com/in/michelle-yen-tran-6212244a/"

[[social]]
  icon = "orcid"
  icon_pack = "ai"
  link = "https://orcid.org/0000-0003-3472-0471"
+++

*** Skills
- Cell culture engineering and development of scalable purification methods for
  therapeutic recombinant enzymes from mammalian cells and gene therapy vectors
  from Adeno-Associated Viruses and lentivirus.
- Process and technical transfer to manufacturing, product characterization and
  risk assessment for FDA review, and lab automation with TECAN liquid handler.
- Purification and analytical techniques: protein chromatography, zonal
  ultracentrifugation, tangential flow filtration, membrane filtration,
  endotoxin-free material production, enzymatic activity assays, HPLC/UPLC
  assays (i.e. size exclusion, reverse phase, weak cation exchange), bio-layer
  interferometry assays, ELISA, qPCR, PicoGreen dsDNA quantification, western
  blots, SDS PAGE, endotoxin testing, AKTA Unicorn chromatography software,
  Agilent HPLC software, Waters UPLC software, and JMP statistical software.

*** Work experience
- Jan 2013 - Aug 2017: Research Associate in the Purification Process
  Development group at BioMarin Pharmaceutical Inc. (Novato, CA, USA)
- Jun 2012 - Aug 2012: Intern for an environmental health science internship
  program (STEER: Short Term Educational Experiences for Research) at University
  of California, Berkeley (USA)
- Feb 2011 - Aug 2012: Research Assistant in Nina Holland’s Children’s
  Environmental Health Laboratory at University of California, Berkeley (USA)"
