+++
# Display name
name = "Alina Venereo Sanchez"

# Username (this should match the folder name)
authors = ["01-alina-venereo-sanchez"]

# Lab position or title
role = "Postdoctoral Fellow (2017-2018)"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Alumni"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = ""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "MSc in Biochemistry: Molecular Biology"
  institution = "University of Havana, Cuba"
  year = "2006-2009"

[[education.courses]]
  course = "BSc in Biology"
  institution = "University of Havana, Cuba"
  year = "2000-2005"

# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "https://ca.linkedin.com/in/alina-venereo-185b8a73"

[[social]]
  icon = "researchgate"
  icon_pack = "fab"
  link = "https://www.researchgate.net/profile/Alina_Venereo"

+++

*** Project
HEK-293 stable cell line development for production, scale up and
characterization of influenza virus-like particles.

*** Work experience
- 2013-2018: As a PhD candidate, experience with cell line development,
  bioprocess optimization, and downstream processing at the National Research
  Council of Canada.
- 2005-2011: Working experience in molecular biology of viral vectors and
  protein expression in mammalian cells mediated by viral vectors (adenovirus,
  lentivirus) for vaccine development. Center of Genetic Engineering and
  Biotechnology (Havana, Cuba).
