+++
# Display name
name = "David Sharon"

# Username (this should match the folder name)
authors = ["david-sharon"]

# Lab position or title
role = "PhD Candidate"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["PhD Candidates"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = """Acceleration and intensification of pandemic influenza vaccine
manufacturing by genetic engineering of the HEK-293SF cell line"""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education 
[[education.courses]]
  course = "MSc in Microbiology and Immunology"
  year = 2015
  institution = "McGill University (Montreal, Canada)"

[[education.courses]]
  course = "Hon. BSc in Biotechnology"
  year = 2012
  institution = "University of British Columbia (Vancouver, Canada)"

[[education.courses]]
  course = "D. Tech in Biotechnology"
  year = 2010
  institution = "British Columbia Institute of Technology (Vancouver, Canada)"
  
# Social/Academic Networking
[[social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.ca/citations?user=dbIYQVoAAAAJ&hl=en"
+++

*** Skills:
- Host-virus interactions
- Molecular biology
- Human genetics.
