+++
# Display name
name = "David Orchard-Webb"

# Username (this should match the folder name)
authors = ["08-david-orchard-webb"]

# Lab position or title
role = "Postdoctoral Fellow"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Alumni"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = ""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "PhD in Cancer Biology"
  institution = "University of Leeds (UK)"

[[education.courses]]
  course = "M.Sc in Molecular and Cellular Biology"
  institution =  "University of Bath (UK)"

# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "https://ca.linkedin.com/in/david-orchard-webb-a49a3187"
+++

*** Project
Adenovirus platforms and cell culture media validation.

*** Work experience
A combined 10 years of basic/ translational cancer research experience at the
Webb-Waring Centre (University of Colorado), University of Bath and University
of Leeds, including the development of adenoviral vectors.
