+++
# Display name
name = "Jean-François Gélinas"

# Username (this should match the folder name)
authors = ["jean-francois-gelinas"]

# Lab position or title
role = "Postdoctoral Fellow"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Postdoctoral Fellows"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = ""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "DPhil in Clinical Laboratory Sciences"
  institution = "University of Oxford (United Kingdom)"
  year = 2017

[[education.courses]]
  course = "MSc in Microbiology and Immunology"
  institution = "McGill University (Montreal, Canada)"
  year = 2010

# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "www.linkedin.com/in/CT-1b025737"
+++

*** Research
My research interests include cell culture engineering, bioprocess optimization
and scale-up, and manufacturaing of antiviral vaccines and viral vectors for
gene derlivery.

*** Project
Removing hurdles to Vesicular Stomatitis Virus vector production
through design of novel bioengineered cell lines.

*** Skills
Viral vector production for viral vectors and vaccines.

*** Work experience
- 2011-2012: Research Specialist in Levine’s Clinical Cell and Vaccine
  Production Facility at the University of Pennsylvania (USA)
- 2010-2011: Research assistant in the Viral Hepatitis Research group at Centre
  de Recherche du CHUM (Montreal, Canada)
