+++
# Display name
name = "Xavier Elisseeff"

# Username (this should match the folder name)
authors = ["xavier-elisseeff"]

# Lab position or title
role = "Research Assistant (2017-2018)"

# Organizational group(s) that the user belongs to. Refer to the 'user_groups'
# variable located at /content/people/people.org for valid options.
user_groups = ["Alumni"]

# List any organizations in the format [ {name="org1", url="url1"}, ... ]
organizations = [ { name = "McGill University", url = "https://www.mcgill.ca/" } ]

bio = ""

# List any interests in the format ["interest1", "interest2"]
interests = []

# Education
[[education.courses]]
  course = "Master of Biology (M.Sc.)"
  institution = "University of Quebec in Montreal (Montreal, Canada)"

[[education.courses]]
  course = "Bachelor of Biology (B.Sc.)"
  institution = "University of Quebec in Montreal (Montreal, Canada)"

# Social/Academic Networking
[[social]]
  icon = "linkedin"
  icon_pack = "fab"
  link = "https://www.linkedin.com/in/xavier-elisseeff-066589b6/"

[[social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.fr/citations?user=TjN416cAAAAJ&hl=fr"

[[social]]
  icon = "researchgate"
  icon_pack = "fab"
  link = "https://www.researchgate.net/profile/Xavier_Elisseeff"
+++

*** Work experience
- July, 2017 - 2018: Research assistant (influenza project) with Prof. Kamen lab,
Bioengineering Department, McGill University. Cellular and molecular biology.
